spring:
  datasource:
    url: jdbc:mysql://119.23.54.62:3306/shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.ljb.sbdemo.models.model
  mapperLocations: classpath:mapper/*.xml
swagger:
    show: true