spring:
  datasource:
    url: jdbc:mysql://119.23.54.62:3306/shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  typeAliasesPackage: com.ljb.sbdemo.models.model
  mapperLocations: classpath*:com/ljb/sbdemo/dao/mapper/*Mapper.xml
swagger:
  show: true
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
server:
  port: 8081